# Generated by Django 3.2.13 on 2022-11-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221116_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=100)),
                ('profile_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movies.Actor'),
        ),
    ]
