# Generated by Django 3.2.13 on 2022-11-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221116_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
