# Generated by Django 3.2.13 on 2022-11-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_actor_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
